# Dependencies
markdown:         kramdown
highlighter:      pygments

kramdown:
  input: GFM

# Setup
title:               Acyclic.eu
tagline:             'elevating people and products'
description:         'Patrik Gustafsson - Software Engineer, Leader, and Product Developer'
url:                 'https://acyclic.eu/'
baseurl:             '/'
paginate:            5
permalink:           pretty
paginate_path:       "blog/page:num"
banner:              "banner.jpg"
banner_alt_text:     "banner"

# About/contact
author:
  name:              Patrik Gustafsson
  url:               https://bsky.app/profile/acyclic.eu
  email:             contact@acyclic.eu

# Custom vars
version:          0.0.2
google_analytics_id: #UA-XXXX-Y

github:
  repo:           https://github.com/acyclic-eu/acyclic-eu.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap

first_page:
  url: index
